### ISSUE TITLE
Save snapshot image

### ISSUE THREAD

**Issue by pablomelo** [nuveo/gofn#45]
As a user,
I want to save a snapshot created by gofn,
So I can re-utilize it when I need to run the same stuff

**Comment by cassiobotaro** [comment]
https://github.com/nuveo/gofn/blob/master/gofn.go#L15-L28 returns a machine that  already do that.

See here: https://github.com/nuveo/gofn/blob/master/iaas/digitalocean/digitalocean.go#L313.
