### ISSUE TITLE
Other output formats

### ISSUE THREAD

**Issue by crgimenes** [nuveo/gofn#5]
How about one parameter to allow other output formats?
JSON is the default but a parameter could allow other formats such as XML, CSV, raw, etc.

**Comment by jwendell** [comment]
Why is there such requirement at all? The output interpretation should be up to the caller. Gofn app itself should be agnostic regarding this...

**Comment by avelino** [comment]
@jwendell the gofn knowing the return type know if processed properly the container, if he gives some error in the middle of the process we have no way to validate

**Comment by jwendell** [comment]
That's exactly the point. gofn as a tool shouldn't be the guy processing the image's output.
If I understand correctly, the gofn use case is:

> Hey, I have some computing to do, let me use this tool so that it does the job somewhere (docker, aws, etc) and give me the output.

So, it's the responsibility of the user to tell whether the computing has succeed or not. Whether the user expects a json, xml, plain text, whatever as a result, it doesn't matter to gofn (or it shouldn't).

**Comment by avelino** [comment]
This is exactly the thought that we need.
@crgimenes @marioidival @cassiobotaro @gtsalles @pablomelo @felipeweb 

comment pls

**Comment by felipeweb** [comment]
Today gofn just get stdout we don't check what is the output format and IMHO should continue in this way
