### ISSUE TITLE
Two concurrent gofn calls passing stdin might cause a race condition

### ISSUE THREAD

**Issue by pablomelo** [nuveo/gofn#51]
At the moment, the STDIN parameter is set on the "global variable" Input (https://github.com/nuveo/gofn/blob/f374c1f89f1ec8ec1911b7754234d9dbbf5eb952/gofn.go#L15) and will potentially cause problems when two routines are passing data through it, at the same time.

**Comment by avelino** [comment]
move the statement into the `Run` solve?

**Comment by pablomelo** [comment]
I would think so.
