### ISSUE TITLE
Digital Ocean support

### ISSUE THREAD

**Issue by avelino** [nuveo/gofn#7]
`gofn` must be able to create a Digital Ocean machine (based on a Digital Ocean snapshot that has installed docker).

After creating the machine, run the container inside the machine and `gofn` get the stdout.

- [x] define interface for iaas
- [x] define a digitalocean iaas
- [x] authenticate in digitalocean
- [x] create a droplet
- [x] generate ssh keys
- [x] if not have a box os snapshot create one
- [x] remove a droplet*
- [x] install box os on new machine

*don't forget to shutdown before

**Comment by felipeweb** [comment]
- [ ] define interface for iaas
- [ ] rewrite the localmode to LocalIaas
- [ ] define a digitalocean iaas
- [ ] authenticate in digitalocean
- [ ] create a droplet
- [ ] remove a droplet
- [ ] generate ssh keys
- [ ] if not have a box os snapshot create one

**Comment by avelino** [comment]
fixed in #32
