### ISSUE TITLE
Support docker volume

### ISSUE THREAD

**Issue by avelino** [nuveo/gofn#8]
Today we are able to put a JSON as a stdout, the idea to mount a volume is to generate a file (when necessary) to return.

Example:
Do crop in an image (big), so the `gofn` would be able to process other file type

**Comment by vmesel** [comment]
Look, I'm not a Go programmer, but I'll try to elucidate this issue for you. The app that runs on the Docker could generate a file on the volume, so the function that is going to be run needs to create a new file on the docker volume, or you could run the docker call with the "docker run ... > file.txt" so you are able to retrieve the output

**Comment by felipeweb** [comment]
@cassiobotaro  can we close this issue?
